import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Inconsolata } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const inconsolata = Inconsolata({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header>
        <svg width="1em" height="1em">
          <linearGradient id="blue-gradient" x1="100%" y1="100%" x2="0%" y2="0%">
            <stop stopColor="#01ECF3" offset="0%" />
            <stop stopColor="#DA107B" offset="100%" />
          </linearGradient>
        </svg>
      </header>

      <body className={`${inter.className} ${inconsolata.className}`}>{children}</body>
      
    </html>
  );
}
